### PR TITLE
Refactor Track --> Clip

### PR DESCRIPTION
**Pull request by justinsalamon**
For non-music audio the term Clip is more appropriate than Track. This PR refactors Track and related variables (e.g. track_id) into Clip (and clip_id, etc.).

### CODE REVIEW

**Comment by justinsalamon** [comment]
@magdalenafuentes once we merge #2 into master I'll merge the upstream changes into this PR

**Comment by justinsalamon** [comment]
@magdalenafuentes let's first review/merge #2 before reviewing this one, since it currently includes the changes from #2 and there's no point reviewing the same changes twice.

**Review by magdalenafuentes — APPROVED** [review]

**Comment by justinsalamon** [comment]
@magdalenafuentes this PR is ready for review

Next I'll start working on the next PR to refactor MultiTrack. My thinking is that we should keep it since it's a useful construct e.g. for source separation (sources + mix), the question is what to call the new class:
* Mix
* Mixture
* MultiClip
* ClipSet
* ClipGroup

Any thoughts?

**Comment by magdalenafuentes** [comment]
@justinsalamon good question... In music datasets `MultiTrack` does work, but don't not beyond that. @pseeth thoughts?

**Comment by pseeth** [comment]
ClipSet or ClipGroup work for me. I think ClipGroup could be nice (as there are a lot of Sets out there, and they are referring to datasets). There's also an affordance for Group coming from DAWs (e.g. grouping tracks to make a submix).

**Pull request merged**
