### PR TITLE
Fix eigenscape

### PR DESCRIPTION
**Pull request by iranroman**
As discussed in #98 and  [`micarraylib` issue #8](https://github.com/micarraylib/micarraylib/issues/8#issuecomment-1095422983), the original `Park6` and `Park8` files got mixed up between the `eigenscape_raw` and `eigenscape` versions by accident. This mix-up happened at the level of the `REMOTES` (i.e. this is not a `soundata` bug but rather an issue identified at the remote dataset host), so a solution for `soundata` is to change the loader `indices` and downloaders to point to the correct files. This PR does that. Merging this PR will solve the issues discussed by #98

### CODE REVIEW

**Comment by iranroman** [comment]
Hello @marc1701, merging this PR will resolve the mismatches found in `eigenscape` and `eigenscape_raw`. You can simply point your fanbase to `soundata` and they will get the correct files. Cheers!

**Comment by marc1701** [comment]
Thanks Iran, much appreciated. I also appreciate the idea that I have a fanbase! Will certainly point users to soundata in any future work.

**Comment by iranroman** [comment]
@magdalenafuentes @pzinemanas please review and let us know your thoughts so that we can merge and address this issue.

**Comment by pzinemanas** [comment]
Hi @iranroman, thanks for addressing this issue. Just for double-checking, did you run the `test_full_dataset` test after making these changes?

**Comment by iranroman** [comment]
Hello @pzinemanas . I just finished running these tests. Since these two dataset are very large, it takes several hours for the tests to download the data and run. They all have passed. We are ready to merge. Thanks!

**Comment by magdalenafuentes** [comment]
@iranroman shouldn't we change the version of the dataset in the index if this is fixed in Zenodo? Also, I see that the `make_index` script didn't change, should we change the version in that script as well?

**Comment by iranroman** [comment]
Hello @magdalenafuentes I've added a "warning" about this engineered solution to each dataset.

**Review by magdalenafuentes — APPROVED** [review]

**Pull request merged**
